"""request booked add

Revision ID: 5e8a2a73a282
Revises: c95a9f5b45bb
Create Date: 2026-05-03 03:07:14.323699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8a2a73a282'
down_revision: Union[str, None] = 'c95a9f5b45bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike_booking_requests',
    sa.Column('driver_user_id', sa.String(length=36), nullable=False),
    sa.Column('bike_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='booking_request_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bikes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_bike_status', 'bike_booking_requests', ['bike_id', 'status'], unique=False)
    op.create_index('ix_booking_driver_status', 'bike_booking_requests', ['driver_user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_driver_status', table_name='bike_booking_requests')
    op.drop_index('ix_booking_bike_status', table_name='bike_booking_requests')
    op.drop_table('bike_booking_requests')
    # ### end Alembic commands ###
