"""otp add

Revision ID: c95a9f5b45bb
Revises: b7f3fb1451f4
Create Date: 2026-04-30 22:40:09.626577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95a9f5b45bb'
down_revision: Union[str, None] = 'b7f3fb1451f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('email', sa.String(length=255), nullable=False))
    op.drop_index('ix_otp_requests_phone_expires', table_name='otp_requests')
    op.create_index(op.f('ix_otp_requests_email'), 'otp_requests', ['email'], unique=False)
    op.create_index('ix_otp_requests_email_expires', 'otp_requests', ['email', 'expires_at'], unique=False)
    op.drop_column('otp_requests', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_requests', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_index('ix_otp_requests_email_expires', table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_email'), table_name='otp_requests')
    op.create_index('ix_otp_requests_phone_expires', 'otp_requests', ['phone', 'expires_at'], unique=False)
    op.drop_column('otp_requests', 'email')
    # ### end Alembic commands ###
